# Generated by Django 4.2.5 on 2024-02-03 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_cover_image_movie_movie_cover_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_director',
            new_name='Director',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_rating',
            new_name='Rating',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_year',
            new_name='Year',
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(auto_created=True, blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_movie_title', to='blog.movie'),
        ),
    ]
