# Generated by Django 4.2.5 on 2024-02-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_movie_director_movie_director_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Director',
            new_name='Director cabecaede',
        ),
    ]
