# Generated by Django 4.2.5 on 2024-02-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_director_movie_director_cabecaede'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Director cabecaede',
            new_name='Director',
        ),
    ]
