# Generated by Django 5.0.1 on 2024-02-05 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_id_movie_movie_id_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_id',
            new_name='id',
        ),
    ]
