# Generated by Django 5.0.1 on 2024-02-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_movie_id_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='static\\media\\movie_covers'),
        ),
    ]
